"""add buyer demands

Revision ID: ee3524af5c26
Revises: aab143fbcd97
Create Date: 2026-02-27 20:35:19.716762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee3524af5c26'
down_revision: Union[str, None] = 'aab143fbcd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_demands',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('buyer_id', app.models.types.GUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('meeting_address', sa.Text(), nullable=False),
    sa.Column('meeting_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('meeting_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('desired_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('obd_requested', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buyer_demand_buyer_status', 'buyer_demands', ['buyer_id', 'status'], unique=False)
    op.create_index('ix_buyer_demand_desired_date', 'buyer_demands', ['desired_date'], unique=False)
    op.create_index('ix_buyer_demand_status_expires', 'buyer_demands', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_buyer_demands_buyer_id'), 'buyer_demands', ['buyer_id'], unique=False)
    op.create_table('demand_interests',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('demand_id', app.models.types.GUID(), nullable=False),
    sa.Column('mechanic_id', app.models.types.GUID(), nullable=False),
    sa.Column('proposal_id', app.models.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['buyer_demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['date_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_id', 'mechanic_id', name='uq_demand_mechanic')
    )
    op.create_index('ix_demand_interest_demand', 'demand_interests', ['demand_id'], unique=False)
    op.create_index('ix_demand_interest_mechanic', 'demand_interests', ['mechanic_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('availabilities', 'is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_availabilities_mechanic_date', table_name='availabilities')
    op.drop_index('ix_availability_date', table_name='availabilities')
    op.create_index('ix_availability_mechanic_date', 'availabilities', ['mechanic_id', 'date'], unique=False)
    op.alter_column('blacklisted_tokens', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.types.GUID(),
               existing_nullable=False)
    op.alter_column('blacklisted_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'check_in_code_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_bookings_buyer_status_created', table_name='bookings')
    op.drop_index('ix_bookings_mechanic_status_created', table_name='bookings')
    op.drop_index('ix_bookings_stripe_payment_intent_id', table_name='bookings')
    op.create_index(op.f('ix_bookings_stripe_payment_intent_id'), 'bookings', ['stripe_payment_intent_id'], unique=True)
    op.alter_column('date_proposals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diplomas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispute_cases', 'opened_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('dispute_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('dispute_cases_opened_by_fkey', 'dispute_cases', type_='foreignkey')
    op.drop_constraint('dispute_cases_resolved_by_admin_fkey', 'dispute_cases', type_='foreignkey')
    op.create_foreign_key(None, 'dispute_cases', 'users', ['opened_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dispute_cases', 'users', ['resolved_by_admin'], ['id'], ondelete='SET NULL')
    op.alter_column('inspection_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mechanic_profiles', 'rating_avg',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    op.alter_column('mechanic_profiles', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mechanic_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mechanic_profiles', 'has_cv',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mechanic_profiles', 'no_show_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mechanic_profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mechanic_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mechanic_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('mechanic_profiles_user_id_fkey', 'mechanic_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'mechanic_profiles', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.alter_column('processed_webhook_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('referral_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_reviews_reviewer_id', table_name='reviews')
    op.drop_constraint('reviews_reviewer_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_reviewee_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['reviewee_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('validation_proofs', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_proofs', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_reviewee_id_fkey', 'reviews', 'users', ['reviewee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reviews_reviewer_id_fkey', 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('referral_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('processed_webhook_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', sa.text('created_at DESC')], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'mechanic_profiles', type_='foreignkey')
    op.create_foreign_key('mechanic_profiles_user_id_fkey', 'mechanic_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('mechanic_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mechanic_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mechanic_profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mechanic_profiles', 'no_show_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mechanic_profiles', 'has_cv',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mechanic_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mechanic_profiles', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mechanic_profiles', 'rating_avg',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    op.alter_column('inspection_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'dispute_cases', type_='foreignkey')
    op.drop_constraint(None, 'dispute_cases', type_='foreignkey')
    op.create_foreign_key('dispute_cases_resolved_by_admin_fkey', 'dispute_cases', 'users', ['resolved_by_admin'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('dispute_cases_opened_by_fkey', 'dispute_cases', 'users', ['opened_by'], ['id'], ondelete='CASCADE')
    op.alter_column('dispute_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispute_cases', 'opened_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('diplomas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('date_proposals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bookings_stripe_payment_intent_id'), table_name='bookings')
    op.create_index('ix_bookings_stripe_payment_intent_id', 'bookings', ['stripe_payment_intent_id'], unique=False)
    op.create_index('ix_bookings_mechanic_status_created', 'bookings', ['mechanic_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_bookings_buyer_status_created', 'bookings', ['buyer_id', 'status', 'created_at'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'check_in_code_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blacklisted_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('blacklisted_tokens', 'id',
               existing_type=app.models.types.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index('ix_availability_mechanic_date', table_name='availabilities')
    op.create_index('ix_availability_date', 'availabilities', ['date'], unique=False)
    op.create_index('ix_availabilities_mechanic_date', 'availabilities', ['mechanic_id', 'date'], unique=False)
    op.alter_column('availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('availabilities', 'is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_demand_interest_mechanic', table_name='demand_interests')
    op.drop_index('ix_demand_interest_demand', table_name='demand_interests')
    op.drop_table('demand_interests')
    op.drop_index(op.f('ix_buyer_demands_buyer_id'), table_name='buyer_demands')
    op.drop_index('ix_buyer_demand_status_expires', table_name='buyer_demands')
    op.drop_index('ix_buyer_demand_desired_date', table_name='buyer_demands')
    op.drop_index('ix_buyer_demand_buyer_status', table_name='buyer_demands')
    op.drop_table('buyer_demands')
    # ### end Alembic commands ###
